### ISSUE TITLE
Execute javascript over https base url

### ISSUE THREAD

**Issue by ealves** [ealves/protractor-recorder#1]
Problem when try to execute javascript with non https src.

**Comment by ealves** [comment]
May be this will need a proxy to work with selenium and socket.io.

**Comment by magestican** [comment]
Will start working on this

**Comment by rominoushana** [comment]
If this problem can be fixed, that would be perfect. I am in extreme need of this project.

**Comment by xunwu** [comment]
Yeah, I also meet this situation, anyone can solve it ?

**Comment by simar0at** [comment]
I have no solution but a workaround: Use https://mitmproxy.org/ . Start it in reverse proxy mode -R https://{your server} and you can use http://localhost:8080/ as a replacement for your real url. The injection of the JavaScripts that record your interactions works then. You can replay your recorded actions on any site with https.

**Comment by magestican** [comment]
I just created a PR with a fix for this issue, please comment there if it works and if so lets merge it :) @ealves

**Comment by ealves** [comment]
This issue is not a bug, it's a enhancement. Once you are not developing in a https and can’t control https, i suggest to not use this project.

This tool is for end to end tests and not to validate integrations between different systems. I suggest another tool to extract informations, like crawlers.

The idea besides using https is just to test in a production environment under control.
So, you’ll need to run the selenium web driver under https too and not only the protractor recorder.

Maybe something is missing or you have to describe some new steps to configure it right. Your PR doesn’t work for me @magestican

**Comment by aggro80** [comment]
@magestican I get this error in Windows 7:
node v7.9.0
npm 4.2.0
```
[08:31:19] Using gulpfile C:\proto\record\protractor-recorder\gulpfile.js
[08:31:19] Starting 'express'...
[08:32:02] Finished 'express' after 43 s
[08:32:02] Starting 'livereload'...
[08:32:04] Finished 'livereload' after 1.94 s
[08:32:04] Starting 'watch'...
[08:32:07] Finished 'watch' after 3.79 s
[08:32:07] Starting 'default'...
[08:32:07] Finished 'default' after 92 µs
C:\proto\record\protractor-recorder\server.js:339
    var httpsExpressServer = https.createServer({key: keys.serviceKey, cert: keys.certificate}, app)
                                                          ^

TypeError: Cannot read property 'serviceKey' of undefined
    at C:\proto\record\protractor-recorder\server.js:339:59
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:278:24
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:168:24
    at done (C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:78:24)
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:91:13
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:1044:20
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:1027:9
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:937:20
    at C:\proto\record\protractor-recorder\node_modules\pem\lib\pem.js:1092:20
    at F (C:\proto\record\protractor-recorder\node_modules\which\which.js:68:16)
```

**Comment by aggro80** [comment]
@ealves Just FYI that we have a project which does not have ideal setup. We can test the system partially with HTTP, but HTTPS is pretty much required for us so that we can do full end to end testing. Is there any hope to see HTTPS support in the near future? And do you know how to run selenium web driver in HTTPS-mode?
