### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by kcampion** [ealves/protractor-recorder#17]
When I click on export button, this error appears:
```
POST http://localhost:9000/export 500 (Internal Server Error)

TypeError: Cannot read property 'forEach' of undefined
   at /projects/protractor-recorder/server.js:184:15
   at Array.forEach (native)
   at /projects/protractor-recorder/server.js:181:21
   at Layer.handle [as handle_request] (/projects/protractor-recorder/node_modules/express/lib/router/layer.js:95:5)
   at next (/projects/protractor-recorder/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/projects/protractor-recorder/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/projects/protractor-recorder/node_modules/express/lib/router/layer.js:95:5)
   at /projects/protractor-recorder/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/projects/protractor-recorder/node_modules/express/lib/router/index.js:330:12)
   at next (/projects/protractor-recorder/node_modules/express/lib/router/index.js:271:10)
``` 

Under logs of server.js, I've this warning:
```
# node server.js
Server listening on *:9000
a user connected
WARNING - pattern spec.js did not match any files.
```

**Comment by ealves** [comment]
Hi @kcampion. Try to clear your local storage too and run all again. Report any error if problem persist.

**Comment by kcampion** [comment]
It works fine now with the local storage cleared.
