### ISSUE TITLE
When try to record, my base url website is not loading. 

### ISSUE THREAD

**Issue by meetbaluyogi** [ealves/protractor-recorder#53]
Got this error in console. 
{"state":"unhandled error","sessionId":null,"hCode":104328532,"value":{"additionalInformation":"\nDriver info: driver.version: unknown","localizedMessage":"GET /session\nBuild info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'\nSystem info: host: 'Bala', ip: '192.168.50.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9'\nDriver info: driver.version: unknown","systemInformation":"System info: host: 'Bala', ip: '192.168.50.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9'","supportUrl":null,"cause":null,"suppressed":[],"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"message":"GET /session\nBuild info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'\nSystem info: host: 'Bala', ip: '192.168.50.220', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9'\nDriver info: driver.version: unknown","hCode":1575083024,"class":"org.openqa.selenium.UnsupportedCommandException","buildInformation":null},"class":"org.openqa.selenium.remote.Response","status":13}

![image](https://user-images.githubusercontent.com/42961110/45019380-d48e5900-b049-11e8-9766-4491806bccf9.png)

15:45:04.471 INFO - Selenium Server is up and running
15:45:28.415 INFO - Executing: [new session: Capabilities [{acceptSSlCerts=true, browserName=chrome}]])
15:45:28.573 INFO - Creating a new session for Capabilities [{acceptSSlCerts=true, browserName=chrome}]
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 1166
Only local connections are allowed.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openqa.selenium.os.ProcessUtils (file:/C:/Users/Bala/AppData/Roaming/npm/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar) to field java.lang.ProcessImpl.handle
WARNING: Please consider reporting this to the maintainers of org.openqa.selenium.os.ProcessUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:45:34.287 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Bala', ip: '192.168.50.218', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9'
Driver info: driver.version: unknown
        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
        at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)

**Comment by prasathmscss** [comment]
Please help me to install this protractor recorder

**Comment by prasathmscss** [comment]
how i need to add conf.js
which folder i need to add conf.js

**Comment by prasathmscss** [comment]
Hi,

Please find the below image,
![protractor run](https://user-images.githubusercontent.com/28854326/56110111-e71e2880-5f70-11e9-82a5-be429d70f447.png)

how i need to add conf.js
send me code for conf.js
which folder i need to add conf.js
